### PR TITLE
Change details of a used fixture

### PR DESCRIPTION
**Pull request by jml**
I want to be able to have a fixture that uses other fixtures but changes the details that they provide. I want to be able to do this without subclassing them.

Since 354acf568aa86bb7d43a01c23d73c750f601b335, it has not been possible to do this. The attached test demonstrates the failure mode.

```
$ make check
python -m testtools.run fixtures.test_suite
Tests running...
======================================================================
ERROR: fixtures.tests.test_fixture.TestFixture.test_change_details_in_used_fixture
----------------------------------------------------------------------
Traceback (most recent call last):
  File "fixtures/tests/test_fixture.py", line 296, in test_change_details_in_used_fixture
    'bar': text_content('oof')}, b.getDetails())
  File "fixtures/fixture.py", line 156, in __exit__
    self._cleanups()
  File "fixtures/callmany.py", line 89, in __call__
    reraise(error[0], error[1], error[2])
  File "fixtures/callmany.py", line 83, in __call__
    cleanup(*args, **kwargs)
  File "fixtures/tests/test_fixture.py", line 289, in _post_process_details
    foo = self.getDetails()['foo']
  File "fixtures/fixture.py", line 171, in getDetails
    combine_details(source.getDetails(), result)
  File "fixtures/fixture.py", line 169, in getDetails
    result = dict(self._details)
TypeError: 'NoneType' object is not iterable
```

Note that `setUp` works just fine in both fixtures. 

This is related to testing-cabal/testtools#167.

[Review on Reviewable](https://reviewable.io/reviews/testing-cabal/fixtures/20)

### CODE REVIEW

**Comment by tomprince** [comment]
I don't think that you can use a cleanup in a fixture to update details. Looking at the [testtools code](https://github.com/testing-cabal/testtools/blob/master/testtools/testcase.py#L681-L683) that uses fixtures, details are looked at before cleanups on the fixture are called.

https://github.com/jml/fixtures/pull/1 demonstrates how to change the details of a fixture.

**Comment by jml** [comment]
> I don't think that you can use a cleanup in a fixture to update details. Looking at the testtools code that uses fixtures, details are looked at before cleanups on the fixture are called.

That's sort of my point. 

I take an approach similar to jml#1 in testing-cabal/testtools#171. Unfortunately, this approach doesn't work very well if you want to mutate a detail and give it the same name. That is, if you want to update the detail `foo` to something that depends on the original value of the detail `foo`. If you try that, you will get infinite recursion.

**Comment by jml** [comment]
I think what I actually want is an overridable method on `Fixture` that is given the detail dict and returns a new detail dict, and for this new detail dict to be used as the official details of the fixture when that is gathered.

In particular, I don't want to have to think about state, especially not the internal state of the fixture object.

**Comment by jml** [comment]
I'll try to come back to this with a patch that provides a hook. In the meantime, closing because I'd rather @rbtcollins attention be spent on other PRs.

**Pull request closed without merging**
