### PR TITLE
Add CompoundFixture

### PR DESCRIPTION
**Pull request by jml**
Allows multiple fixtures to be combined.

Chucking this one over the wall, I'm afraid. Pretty low down the priority queue, and both ClusterHQ and myself are struggling to find spare cycles.

[Review on Reviewable](https://reviewable.io/reviews/testing-cabal/fixtures/22)

### CODE REVIEW

**Comment by rbtcollins** [comment]
I'm not sure if this should be in fixture.py or in _fixtures somewhere.

Its missing documentation.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[fixtures/fixture.py, line 422 \[r1\]](https://reviewable.io:443/reviews/testing-cabal/fixtures/22#-K9AeF-CNDI_jPTjwtWv:-K9AeF-CNDI_jPTjwtWw:1348720771) ([raw file](https://github.com/testing-cabal/fixtures/blob/baead46324b607a9006debf45bd030d59ffa5d84/fixtures/fixture.py#L422)):*
This doesn't bind the result anywhere where folk can access it. Does that matter to you ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/testing-cabal/fixtures/22#-:-K9AeJ_BV1glrlV7YQfv:241307716)*

**Comment by jml** [comment]
I put it in `fixture.py` because `MethodFixture` was in there.

Documentation added (also NEWS).

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[fixtures/fixture.py, line 422 \[r1\]](https://reviewable.io:443/reviews/testing-cabal/fixtures/22#-K9AeF-CNDI_jPTjwtWv:-K9BTHK8jNYLLZAET3iq:-523672119) ([raw file](https://github.com/testing-cabal/fixtures/blob/baead46324b607a9006debf45bd030d59ffa5d84/fixtures/fixture.py#L422)):*
So far, no use case for that myself, but writing docs made it apparent that someone else might want it. Taken the easiest route and renamed `_fixtures` to `fixtures`, documenting that you shouldn't mutate it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/testing-cabal/fixtures/22#-:-K9BTO70bxvw5LsUnSlj:-1389622592)*

**Comment by rbtcollins** [comment]
Looks fine to me.

I wonder if we could do something nice with setattr. hypothetically:

```
>>> c = CleverCompoundFixture()
>>> c.noddy = NoddyFixture
>>> c.log = LoggingFixture()
>>> with c:
>>>     c.noddy.frobnozzle
42
```

A builder style interface could be used to avoid this being a mutate-in-place API.

---

Reviewed 1 of 2 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/testing-cabal/fixtures/22#-:-K9DXsxBu-iqtETRBKus:575351498)*

**Comment by jml** [comment]
Thanks!

I think I'd probably lean toward something like:

```python
fixture = NamedFixtures(noddy=NoddyFixture(), log=LogFixture())
with fixture as c:
    c.noddy.frobnozzle
```

I don't think a builder is necessary, but if desired it could be done as a separate class. Instead of a builder, I would tend to rely on existing stuff for building dicts, and passing in as `**kwargs`.

**Comment by jml** [comment]
Merged as  bd43849

**Pull request closed without merging**
