### PR TITLE
Extract function for use_fixture

### PR DESCRIPTION
**Pull request by jml**
Inheritance is so passé. 

Extract a function for calling `use_fixture`. When this is released we can have testtools use it.

[Review on Reviewable](https://reviewable.io/reviews/testing-cabal/fixtures/21)

### CODE REVIEW

**Comment by rbtcollins** [comment]
So, sure - public function, please add to docs and testcase.__all__ at a minimum. I'm not sure this is itself bugfree.

Also I'm not sure what inheritance has to do with it; we already handle fixtures ourselves in testtools?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/testing-cabal/fixtures/21#-:-K9AfA9s3OALHMPZ-UA6:-2141365674)*

**Comment by jml** [comment]
I'd forgotten about this one! Will try to find time to add docs & tests as you suggest, but 

> I'm not sure this is itself bugfree.

It really is just moving code from `TestWithFixtures`. Are you saying that you're not sure that `TestWithFixtures` is bug-free?

> I'm not sure what inheritance has to do with it

`TestWithFixtures` is advertised as a mixin that one can inherit from to get `self.useFixture` on a test case. That's still a thing people could do. However, another way to provide that feature—a way that _doesn't_ use inheritance—is to provide a function people can call.

> we already handle fixtures ourselves in testtools?

Yeah, we [pretty much duplicate this code](https://github.com/testing-cabal/testtools/blob/master/testtools/testcase.py#L669-L697), except, of course, not quite exactly. Wouldn't it be nice to not have subtly different variations of the same code all over the shop? This is a step in that direction.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/testing-cabal/fixtures/21#-:-K9BWG6qISWRLEQ-HsQN:-1302072934)*

**Comment by rbtcollins** [comment]
ping?

**Comment by jml** [comment]
I'm unlikely to find the time to add tests and docs you suggested.

**Comment by jml** [comment]
Don't want this on my Github dashboard. Others are free to re-submit if they'd like.

**Pull request closed without merging**
